Fixes the registry check

diff --git a/bin/y-build b/bin/y-build
--- a/bin/y-build
+++ b/bin/y-build
@@ -16,6 +16,14 @@ BUILDKIT_CACHE="type=registry,ref=localhost:80/ystack:buildcache"
 BUILDCTL_VERSION="buildctl github.com/moby/buildkit v0.6.0 f2d98ca16c87c30bd4a88ca416498cf8a5a96824"
 [ "$(buildctl -v)" != "$BUILDCTL_VERSION"  ] && echo "Requires buildctl '$BUILDCTL_VERSION'; see https://github.com/moby/buildkit/releases" && exit 1
 
+if [ "$(curl -s --connect-timeout 3 http://$REGISTRY/v2/)" != "{}" ]
+then
+  echo "ERROR Skaffold need local access to the builds registry for digest lookup after build"
+  echo "Registry: $REGISTRY"
+  echo "Look for y-stack's ingress or port-forward utilities"
+  exit 1
+fi
+
 # Envs from Skaffold build custom
 # (but for now we simply ignore PUSH_IMAGE as it has no clear significance for in-cluster builds)
 [ -z "$BUILD_CONTEXT" ] && echo "Expected a BUILD_CONTEXT env from Skaffold" && exit 1
@@ -39,13 +47,6 @@ case "$IMAGE" in
 esac
 
 OUTPUT="type=image,name=$IMAGE,push=true,registry.insecure=true"
-
-if ! [ "$(curl -s http://$builds.registry.svc.cluster.local/v2/)" != "{}" ]
-then
-  echo "Skaffold need local access to the builds registry for digest lookup after build"
-  echo "Look for ystacks's ingress or port-forward utilities"
-  exit 1
-fi
 
 echo "Build command:"
 set -x
