GCP project must be overridable

diff --git a/bin/y-cluster-provision-gke-fix-webhooks8443 b/bin/y-cluster-provision-gke-fix-webhooks8443
--- a/bin/y-cluster-provision-gke-fix-webhooks8443
+++ b/bin/y-cluster-provision-gke-fix-webhooks8443
@@ -8,9 +8,14 @@ set -e
 CLUSTER_NAME=$1
 [ -z "$CLUSTER_NAME" ] && echo "First argument must be a cluster name" && exit 1
 
-gcloud container clusters describe $CLUSTER_NAME --region=europe-west4 | grep masterIpv4CidrBlock
+REGION="$2"
+[ -z "$REGION" ] && echo "Second argument must be a gcloud region name" && exit 1
 
-gcloud compute firewall-rules list \
+[ -n "$PROJECT" ] || PROJECT="$(gcloud config get-value project)"
+
+gcloud --project=$PROJECT container clusters describe $CLUSTER_NAME --region=$REGION | grep masterIpv4CidrBlock
+
+gcloud --project=$PROJECT compute firewall-rules list \
     --filter "name~^gke-$CLUSTER_NAME" \
     --format 'table(
         name,
@@ -25,7 +30,7 @@ read -p "What's the targets' hex code above? " TARGET_HEX
 
 TARGET=gke-$CLUSTER_NAME-$TARGET_HEX-node
 FIREWALL_RULE_NAME=gke-$CLUSTER_NAME-$TARGET_HEX-master-webhooks
-MASTER_CIDR_BLOCK=172.16.0.0/28
+[ -z "$MASTER_CIDR_BLOCK" ] && echo "MASTER_CIDR_BLOCK is required, for example MASTER_CIDR_BLOCK=172.16.0.0/28"
 SOURCE_RANGE=$MASTER_CIDR_BLOCK
 PROTOCOL=tcp
 PORT=8443
@@ -34,7 +39,7 @@ PORT=8443
 
 echo "Suggested command:"
 echo \
-gcloud compute firewall-rules create $FIREWALL_RULE_NAME \
+gcloud --project=$PROJECT compute firewall-rules create $FIREWALL_RULE_NAME \
     --action ALLOW \
     --direction INGRESS \
     --source-ranges $SOURCE_RANGE \
